### ISSUE TITLE
KeyError: 'location_base_uris'

### ISSUE THREAD

**Issue by kyao** [brekelma/dsbox_corex#2]
Corex is throwing this error on the 30_personae dataset. Perhaps the metadata has changed?
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 823, in _do_run_step
    self._run_step(step)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 815, in _run_step
    self._run_primitive(step)
  File "/user_opt/dsbox/dsbox-ta2/python/dsbox/template/runtime.py", line 251, in _run_primitive
    super()._run_primitive(this_step)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 720, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 796, in _call_primitive_method
    raise error
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 789, in _call_primitive_method
    result = method(**arguments)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/unsupervised_learning.py", line 49, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/base.py", line 518, in _fit_multi_produce
    fit_result = self.fit(timeout=timeout, iterations=iterations)
  File "/user_opt/dsbox/src/dsbox-corex/corex_text.py", line 138, in fit
    self.training_data = self._process_files(self.training_data)
  File "/user_opt/dsbox/src/dsbox-corex/corex_text.py", line 295, in _process_files
    file_loc = inputs.metadata.query((mbase.ALL_ELEMENTS, column_index))['location_base_uris']
  File "/usr/local/lib/python3.6/dist-packages/frozendict/__init__.py", line 29, in __getitem__
    return self._dict[key]
KeyError: 'location_base_uris'
```

**Comment by kyao** [comment]
@brekelma or @serbanstan Please take a look a the error.

**Comment by serbanstan** [comment]
Should be fixed
